# Generated by Django 3.1.1 on 2020-10-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creates_date',
            new_name='created_date',
        ),
    ]
